# Generated by Django 4.1.3 on 2022-12-06 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0002_alter_article_image"),
        ("articles", "0002_article_likes"),
    ]

    operations = []
