# Generated by Django 4.1.3 on 2022-12-06 11:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_alter_user_followings"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pet",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_set",
                to=settings.AUTH_USER_MODEL,
                verbose_name="집사",
            ),
        ),
    ]
